### ISSUE TITLE
RSVP to event

### ISSUE THREAD

**Issue by msvrtan** [NullTraining/reviewz#24]
Members (and users?) should be able to RSVP to event

For now options are:
- RSVP yes
- RSVP no

![2018-03-10 12 54 30](https://user-images.githubusercontent.com/1780572/37242040-f9cdf9a0-2462-11e8-9d32-f2e0c398ebd6.jpg)

**Comment by zgperak** [comment]
#Would be prudent to add RSVP maybe?
